language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn docs:build
deploy:
  committer_from_gh: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs/.vuepress/dist
  on:
    branch: master
  provider: pages
  repo: datashaman/datashaman.github.io
  skip_cleanup: true
  target_branch: master
